### PR TITLE
docker build pipeline

### PR DESCRIPTION
**Pull request by darodi**
docker build pipeline

- Only one DockerFile for multi arch
- PGID and PUID as env variable when running.
- github workflow for build. 
  - armv7 takes 1h47 to build. Be patient

### CODE REVIEW

**Comment by Xonshiz** [comment]
Will get this in and then try to spend some time revisiting the Travis build. It's.. uh...flaky.

**Comment by darodi** [comment]
@Xonshiz 

Strange, the pipeline didn't run:

> build_and_push / Prepare workflow environment
> The hosted runner: Hosted Agent lost communication with the server. Anything in your workflow that terminates the runner process, starves it for CPU/Memory, or blocks its network access can cause this error.

Could you try running it again?
https://github.com/Xonshiz/comic-dl/actions

It works fine on my fork
https://github.com/darodi/comic-dl/actions

**Comment by Xonshiz** [comment]
yeah I ran it again. Probably timing out.

**Comment by Xonshiz** [comment]
```
error: invalid tag "ghcr.io/Xonshiz/comic-dl:2022.04.09_linux_amd64_nohealthcheck": repository name must be lowercase
Error: buildx failed with: error: invalid tag "ghcr.io/Xonshiz/comic-dl:2022.04.09_linux_amd64_nohealthcheck": repository name must be lowercase
```

That `Xonshiz` got it lol.

**Comment by darodi** [comment]
I'm creating a separated base image for python + pikepdf. It doesn't make sense to build pikepdf every time a line of code is changed in comic-dl. I'll create a PR once the base docker image is built.

Télécharger Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Xonshiz** [comment]
Yeah, that makes sense. While you do that, I'm looking into porting this complete pipeline from Travis to GH Actions. Travis has been buggy for a while now.

**Pull request merged**
