### PR TITLE
readcomiconline domain switch

### PR DESCRIPTION
**Pull request by adam-da-average**
Quick search and replace for:-

ReadComicOnlineTo ->ReadComicOnlineli
Readcomiconline.to -> Readcomiconline.li

### CODE REVIEW

**Comment by adam-da-average** [comment]
Related issue - https://github.com/Xonshiz/comic-dl/issues/282

**Comment by adam-da-average** [comment]
@Zaccigator - I have only done this as a find and replace for any mentions of the old URL. When I've got some time I can compile it and release it under my own fork until this is accepted in to main.

**Comment by Xonshiz** [comment]
That CI build seems to be failing. I have to see why it's failing before merging this change. I'll take a look at this over this weekend and merge if things are fine.

**Comment by Xonshiz** [comment]
Yep, it's failing before that itself. So, I'll fix that first and then merge. Have some things to do with this repository as well, like automate binary generation (like I did for hulu subs repo) and will test this merge to see if it's working or not.

**Comment by Xonshiz** [comment]
Code merged and the binary should be available as soon as the travis build is done.

**Pull request merged**
