### PR TITLE
improve ignores

### PR DESCRIPTION
**Pull request by darodi**
improve ignores

### CODE REVIEW

**Comment by darodi** [comment]
added cookie in config.json.example
or you might get: 

```
d:\downloads\Apps\comic-dl>cli.py -a
Traceback (most recent call last):
  File "D:\downloads\Apps\comic-dl\cli.py", line 7, in <module>
    main()
  File "D:\downloads\Apps\comic-dl\comic_dl\__main__.py", line 15, in main
    ComicDL(sys.argv[1:])
  File "D:\downloads\Apps\comic-dl\comic_dl\comic_dl.py", line 214, in __init__
    manual_cookie = data["cookie"]
KeyError: 'cookie'

```

**Comment by Xonshiz** [comment]
@darodi  could you please address that comment I added in the previous `.dockerignore` file? I'll merge this PR.

Also, thanks for catching that missing cookie.

**Comment by darodi** [comment]
I don't see, where is the comment?

**Comment by Xonshiz** [comment]
`.dockerignore` line 12. Instead of "changelog.md`, could you make it `*.md`. Better ignore all `.md` files instead of changelog.

**Review by Xonshiz — APPROVED** [review]

**Pull request merged**
