### PR TITLE
Removed python2 style print statement that makes python3 execution crash

### PR DESCRIPTION
**Pull request by jaiakt**
Multiple python2 style print statements are changed into python3 style statements.  This prevents the program from crashing when run on python3 interpreter.

### CODE REVIEW

**Comment by amorino** [comment]
Any ETA on when this will be merged?

**Comment by jaiakt** [comment]
I don't have write access so I can't merge it.  So just waiting for someone with access to merge it.

**Comment by Xonshiz** [comment]
I'll check and merge this weekend.

**Comment by Xonshiz** [comment]
Thanks for the fix :)

**Pull request merged**
