### PR TITLE
 Download all the pages in the same time

### PR DESCRIPTION
**Pull request by dsanchezseco**
Refeers #123 

For now it's done in the following sites:

* Mangarock
* readcomicsbooksonline
* readcomiconline
* readcomicsIO
* readcomicswebsite
* striputopia
* MangaFox

Although some sites it says are not supported(change of domain) or down.

I'll keep working on it.

BTW the progress bar is broken with the multi-threading, so needs some love.
screen shot 2018-06-20 at 21 32 11

### CODE REVIEW

**Comment by darodi** [comment]
@dsanchezseco 
I think this commit https://github.com/Xonshiz/comic-dl/pull/146/commits/6b4b0986b7806e21a6ffd3ce59b08238a52005fe will break the "prepend zeroes" for mangafox.
the downloader function was using "file_name_custom" instead of "file_name"

**Comment by dsanchezseco** [comment]
@darodi  you're right, nice catch. I'd noticed that some sites use different var names for the same data. I'll pay more attention.

**Comment by Xonshiz** [comment]
I am not sure whether this one should be merged or not. Reason being, we do not want the downloader info to be messed up. Let's try to get that working properly first. I haven't been able to follow up the conversation in #123 properly.

**Comment by Xonshiz** [comment]
@dsanchezseco maybe pull this one in the dev branch, so that we can merge it there and release those builds as well. So, people can go for it, meanwhile we fix the progress bar. What do you say?

**Comment by Xonshiz** [comment]
As [discussed](https://github.com/Xonshiz/comic-dl/issues/123#issuecomment-408400397), I'm rejecting this one.

**Pull request closed without merging**
