### PR TITLE
cleanup mangaEden

### PR DESCRIPTION
**Pull request by darodi**
cleanup mangaEden

### CODE REVIEW

**Comment by darodi** [comment]
- fix #273

**Comment by Xonshiz** [comment]
Thanks for cleaning this up, but give me some time and see if there's any alternatives.

**Comment by darodi** [comment]
@Xonshiz 

6 months later, the site is still down. 
Time to clean it up?

**Comment by Xonshiz** [comment]
Hmm yeah, looks like it. Thanks for the cleanup, can you please bump up the version as well and update the change log as well?

**Comment by darodi** [comment]
@Xonshiz 

done

> Hmm yeah, looks like it. Thanks for the cleanup, can you please bump up the version as well and update the change log as well?

**Review by Xonshiz — APPROVED** [review]
Thanks for the cleanup :)

**Pull request merged**
